### ISSUE TITLE
neural-ode compatibility with dm-haiku models ? 

### ISSUE THREAD

**Issue by thibmonsel** [patrick-kidger/diffrax#108]
I am currently following the Neural-ODE tutorial on the Diffrax documentation (`https://docs.kidger.site/diffrax/examples/neural_ode/`). I was wondering if  instead of instantiating Equinox modules the `Func` and `NeuralODE`  there is a work around to incorporate Haiku modules (`hk.Module`) ? 

My end goal would be to use ` diffrax.diffeqsolve` on a ode term that uses `hk.Module` as such : 
```
solution = diffrax.diffeqsolve(
            diffrax.ODETerm(self.func),
            diffrax.Tsit5(),
            t0=ts[0],
            t1=ts[-1],
            dt0=ts[1] - ts[0],
            y0=y0,
            stepsize_controller=diffrax.PIDController(rtol=1e-3, atol=1e-6),
            saveat=diffrax.SaveAt(ts=ts),  # saving all of the intermediate states (disc then opt)
        )
```
where ``` self.func = Func() ``` and ```Func``` is a Haiku module as below : 

```
class Func(hk.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.layers = []
        for out_shape in [2,10]:
            self.layers.append(hk.Linear(out_shape, name=name))
            self.layers.append(jax.nn.relu)
        self.layers.append(hk.Linear(1, name=name))

    def __call__(self, x):
        for layer in self.layers:
            x = layer(x)
        return x
```

**Comment by patrick-kidger** [comment]
Yes, this should be possible. You'll want to set up your Haiku Module in the usual way, and then use `hk.transform` to convert it into functional form. At that point you should be able to use it like other JAX operations, and in particular use it with Diffrax.

**Comment by thibmonsel** [comment]
I did a minimal setup and it doesn't seem to be working, maybe im not setting up right my haiku modules for diffrax.

Relevant imports : 

```
import jax
import optax
import diffrax
import haiku as hk
import jax.numpy as jnp
import jax.random as jrandom
import matplotlib.pyplot as plt
```

So I create a ```Func``` haiku module
```

class Func(hk.Module):
    def __init__(self, output_sizes: list, name=None):
        super().__init__(name=name)
        self.output_sizes = output_sizes
        self.layers = []
        for out_shape in self.output_sizes[:-1]:
            self.layers.append(hk.Linear(out_shape, name=name))
            self.layers.append(jax.nn.relu)
        self.layers.append(hk.Linear(output_sizes[-1], name=name))

    def __call__(self, t, x):
        for layer in self.layers:
            x = layer(x)
        return x
```

After the ```NeuralODE``` haiku module in which ```diffrax``` is embedded.

```
class NeuralODE(hk.Module):
    def __init__(self, func, name=None, **kwargs):
        super().__init__(name=name, **kwargs)
        self.func = func

    def __call__(self, ts, y0):
        solution = diffrax.diffeqsolve(
            diffrax.ODETerm(self.func),
            diffrax.Tsit5(),
            t0=ts[0],
            t1=ts[-1],
            dt0=ts[1] - ts[0],
            y0=y0,
            stepsize_controller=diffrax.PIDController(rtol=1e-3, atol=1e-6),
            saveat=diffrax.SaveAt(ts=ts),  # saving all of the intermediate states (disc then opt)
        )
        return solution.ys
```

If i instantiate separately ```Func``` and ```NeuralODE```, this what i get : 

For ```Func``` i execute : 

```
def fullyconnectedtime(t, x):
    net = Func(output_sizes=[2, 10, 2])
    return net(None, x)

ts = jnp.linspace(0, 10, 100)
y0 = jnp.array([[1.0, 1.0]]).reshape(1, 2)
rng_key = jax.random.PRNGKey(42)

fc = hk.without_apply_rng(hk.transform(fullyconnectedtime))
print(fc, fc.init)
params = fc.init(rng=rng_key, t=ts, x=y0)
print(params)
```

All works well : 

```
Transformed(init=<function without_state.<locals>.init_fn at 0x7f8bcc0c7f70>, apply=<function without_apply_rng.<locals>.apply_fn at 0x7f8bcc0c7dc0>) <function without_state.<locals>.init_fn at 0x7f8bcc0c7f70>
{'func/~/linear': {'w': DeviceArray([[-0.38112733,  0.5898071 ],
             [-0.61969763,  0.9433998 ]], dtype=float32), 'b': DeviceArray([0., 0.], dtype=float32)}, 'func/~/linear_1': {'w': DeviceArray([[-3.6129221e-01,  1.4063759e+00,  3.0642418e-02,
               1.8820369e-01, -6.8864852e-01, -1.0470384e+00,
              -4.8722818e-01, -8.1236870e-04, -5.3821939e-01,
               6.7414087e-01],
             [ 1.7382452e-01,  7.1142066e-01,  5.2265316e-01,
               3.5907748e-01, -5.4773426e-01, -3.7921360e-01,
               5.3152210e-01,  1.1119201e+00,  8.4750330e-01,
              -7.2356480e-01]], dtype=float32), 'b': DeviceArray([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)}, 'func/~/linear_2': {'w': DeviceArray([[ 0.6146172 , -0.03788226],
             [-0.08335911,  0.01174401],
             [-0.03703073, -0.19763884],
             [-0.4531952 ,  0.41499436],
             [-0.44988102, -0.24616808],
             [ 0.54624754, -0.37841237],
             [ 0.17456615,  0.1505136 ],
             [ 0.04238725, -0.34669274],
             [ 0.47925627,  0.45780745],
             [-0.44254103,  0.22282517]], dtype=float32), 'b': DeviceArray([0., 0.], dtype=float32)}}
```

But now if I get to use ```NeuralODE``` all together as such where in the ```network``` function the ```Func``` haiku module is converted in functional form : 

```
def network(ts, y0):
    func = hk.without_apply_rng(hk.transform(fullyconnectedtime))
    net = NeuralODE(func)
    return net(ts, y0)

def fullyconnectedtime(t, x):
    net = Func(output_sizes=[2, 10, 2])
    return net(None, x)

ts = jnp.linspace(0, 10, 100)
y0 = jnp.array([[1.0, 1.0]]).reshape(1, 2)
rng_key = jax.random.PRNGKey(42)

network = hk.without_apply_rng(hk.transform(network))
print(network, network.init)
params = network.init(rng=rng_key, ts=ts, y0=y0)
print(params)
```

it yields : 
```
Transformed(init=<function without_state.<locals>.init_fn at 0x7f25cc206f70>, apply=<function without_apply_rng.<locals>.apply_fn at 0x7f25cc206dc0>) <function without_state.<locals>.init_fn at 0x7f25cc206f70>
Traceback (most recent call last):
  File "/home/monsel/Desktop/neural_ode/model.py", line 109, in <module>
    params = network.init(rng=rng_key, ts=ts, y0=y0)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/haiku/_src/transform.py", line 113, in init_fn
    params, state = f.init(*args, **kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/haiku/_src/transform.py", line 381, in init_fn
    f(*args, **kwargs)
  File "/home/monsel/Desktop/neural_ode/model.py", line 97, in network
    return net(ts, y0)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/haiku/_src/module.py", line 421, in wrapped
    out = f(*args, **kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/haiku/_src/module.py", line 275, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/monsel/Desktop/neural_ode/model.py", line 53, in __call__
    solution = diffrax.diffeqsolve(
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/equinox/jit.py", line 92, in __call__
    return __self._fun_wrapper(False, args, kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/equinox/jit.py", line 88, in _fun_wrapper
    dynamic_out, static_out = self._cached(dynamic, static)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/_src/api.py", line 473, in cache_miss
    out_flat = xla.xla_call(
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/core.py", line 1765, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/core.py", line 1781, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/core.py", line 678, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/_src/dispatch.py", line 182, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/linear_util.py", line 285, in memoized_fun
    ans = call(fun, *args)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/_src/dispatch.py", line 230, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/_src/dispatch.py", line 272, in lower_xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1893, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1865, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/equinox/jit.py", line 39, in fun_wrapped
    out = fun(*args, **kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/diffrax/integrate.py", line 745, in diffeqsolve
    solver_state = solver.init(terms, t0, tnext, y0, args)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/diffrax/solver/runge_kutta.py", line 150, in init
    return terms.vf(t0, y0, args)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/diffrax/term.py", line 396, in vf
    return self.term.vf(t, y, args)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/diffrax/term.py", line 205, in vf
    return self.vector_field(t, y, args)
jax._src.traceback_util.UnfilteredStackTrace: TypeError: 'Transformed' object is not callable

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/monsel/Desktop/neural_ode/model.py", line 109, in <module>
    params = network.init(rng=rng_key, ts=ts, y0=y0)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/haiku/_src/transform.py", line 113, in init_fn
    params, state = f.init(*args, **kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/haiku/_src/transform.py", line 381, in init_fn
    f(*args, **kwargs)
  File "/home/monsel/Desktop/neural_ode/model.py", line 97, in network
    return net(ts, y0)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/haiku/_src/module.py", line 421, in wrapped
    out = f(*args, **kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/haiku/_src/module.py", line 275, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/monsel/Desktop/neural_ode/model.py", line 53, in __call__
    solution = diffrax.diffeqsolve(
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/equinox/jit.py", line 92, in __call__
    return __self._fun_wrapper(False, args, kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/equinox/jit.py", line 88, in _fun_wrapper
    dynamic_out, static_out = self._cached(dynamic, static)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/equinox/jit.py", line 39, in fun_wrapped
    out = fun(*args, **kwargs)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/diffrax/integrate.py", line 745, in diffeqsolve
    solver_state = solver.init(terms, t0, tnext, y0, args)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/diffrax/solver/runge_kutta.py", line 150, in init
    return terms.vf(t0, y0, args)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/diffrax/term.py", line 396, in vf
    return self.term.vf(t, y, args)
  File "/home/monsel/miniconda3/envs/ode2/lib/python3.9/site-packages/diffrax/term.py", line 205, in vf
    return self.vector_field(t, y, args)
TypeError: 'Transformed' object is not callable
```
Im not sure if im doing something wrong or not.

Relevant versions of the packages (up to date i think) are : 

```
diffrax==0.1.2
dm-haiku==0.0.6
jaxlib==0.3.10+cuda11.cudnn82
jax==0.3.13

equinox==0.5.0
```

**Comment by patrick-kidger** [comment]
As the error says, transformed Haiku objects are not callable. You want `transformed_object.apply`.

**Comment by thibmonsel** [comment]
Im not sure to understand, in order to use ```transformed_object.apply``` we need the params of our model that is given by invoking the ```transformed_object.init```

**Comment by patrick-kidger** [comment]
That's correct. I don't think you're doing anything like that at the moment. So you'll need to pass those `params` through to the vector field each time you call it.

i.e. something like
```python
class Network(hk.Module):
    ...

    def __call__(self, t, y, args):
        ...

network = hk.without_apply_rng(hk.transform(...))
params = network.init(...)
vector_field = functools.partial(network.apply, params)
diffeqsolve(ODETerm(vector_field), ...)
```

This issue isn't anything to do with Diffrax I'm afraid; what you're describing are difficulties with Haiku. If you want to use Haiku then I suggest reading up on how to use Haiku, and perhaps trying it in a non-neural-ODE context first to gain familiarity with that library.
