### ISSUE TITLE
Dense solution: memory usage 1000 times higher in Diffrax 0.3

### ISSUE THREAD

**Issue by slishak** [patrick-kidger/diffrax#250]
Hi @patrick-kidger,

I just updated `diffrax` to latest (0.3.1) and tried to run some slightly older code. I found I was getting memory usage errors that I wasn't getting with 0.2.2 when interpolating dense solutions. I've got a minimum reproducible example below based on your Lotka–Volterra example.

```python
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
from diffrax import diffeqsolve, ODETerm, SaveAt, Tsit5


def vector_field(t, y, args):
    prey, predator = y
    α, β, γ, δ = args
    d_prey = α * prey - β * prey * predator
    d_predator = -γ * predator + δ * prey * predator
    d_y = d_prey, d_predator
    return d_y


term = ODETerm(vector_field)
solver = Tsit5()
t0 = 0
t1 = 140
dt0 = 0.1
y0 = (10.0, 10.0)
args = (0.1, 0.02, 0.4, 0.02)
saveat = SaveAt(dense=True)  # Modified here to save dense solution

sol = diffeqsolve(term, solver, t0, t1, dt0, y0, args=args, saveat=saveat)

# Added: interpolate dense solution on very fine grid
t_dense = jnp.linspace(t0, t1, int(1e9))
y_dense = jax.vmap(sol.evaluate)(t_dense)
```

With `diffrax 0.3.1`, this requires 16TB of memory:
```
Traceback (most recent call last):
  File "/home/sam/code/cvsx/sandbox_diffrax.py", line 30, in <module>
    y_dense = jax.vmap(sol.evaluate)(t_dense)
  File "/home/sam/code/cvsx/.venv/lib/python3.10/site-packages/diffrax/solution.py", line 117, in evaluate
    return self.interpolation.evaluate(t0, t1, left)
  File "/home/sam/code/cvsx/.venv/lib/python3.10/site-packages/equinox/_jit.py", line 99, in __call__
    return self._call(False, args, kwargs)
  File "/home/sam/code/cvsx/.venv/lib/python3.10/site-packages/equinox/_jit.py", line 95, in _call
    out = self._cached(dynamic, static)
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory allocating 16400000000052 bytes.
```

WIth `diffrax 0.2.2`, it only requires 16GB (still fails to run in this instance, but obviously for smaller `t_dense` there are situations where code that works in `0.2.2` will not work in `0.3.1`.
```
Traceback (most recent call last):
  File "/home/sam/code/cvsx/sandbox_diffrax.py", line 28, in <module>
    y_dense = jax.vmap(sol.evaluate)(t_dense)
  File "/home/sam/code/cvsx/.venv/lib/python3.10/site-packages/diffrax/solution.py", line 117, in evaluate
    return self.interpolation.evaluate(t0, t1, left)
  File "/home/sam/code/cvsx/.venv/lib/python3.10/site-packages/equinox/_jit.py", line 99, in __call__
    return self._call(False, args, kwargs)
  File "/home/sam/code/cvsx/.venv/lib/python3.10/site-packages/equinox/_jit.py", line 95, in _call
    out = self._cached(dynamic, static)
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory allocating 64000000048 bytes.
```

The above issue can be circumvented by just using `SaveAt(ts=t_dense)` instead of interpolating the dense solution, but thought it was worth reporting anyway.

Thanks!

**Comment by patrick-kidger** [comment]
Thanks for the report! This should be fixed in #252.
