### ISSUE TITLE
Solving an ODE with a forcing term example fails to run

### ISSUE THREAD

**Issue by nikopoulospet** [patrick-kidger/diffrax#514]
Hi, I have been working with some diffrax code and keep running into the same issue. I found that one of the examples in the docs has the same problem so Im thinking this may be a problem with my package versions.

Copy pasting the code in this [example](https://docs.kidger.site/diffrax/examples/forcing/) from the wiki fails when calling `solve` after taking the gradient. 

relevant installed package versions:

```
python                   3.11.8
jax                      0.4.34
jaxlib                   0.4.34
jaxtyping                0.2.34
equinox                  0.11.7
diffrax                  0.6.0
```

<details>
<summary>Error Message</summary>

```
Traceback (most recent call last):
  File "/Users/peternikopoulos/src/random/jax/diffrax_solve_ode_with_forcing_term.py", line 68, in <module>
    grads = solve(points)
  File "/Users/peternikopoulos/src/random/jax/diffrax_solve_ode_with_forcing_term.py", line 62, in solve
    sol = diffeqsolve(term, solver, t0, t1, dt0, y0, args=interp)
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/diffrax/_integrate.py", line 1337, in diffeqsolve
    final_state, aux_stats = adjoint.loop(
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/diffrax/_adjoint.py", line 292, in loop
    final_state = self._loop(
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/diffrax/_integrate.py", line 621, in loop
    final_state = outer_while_loop(
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/equinox/internal/_loop/loop.py", line 107, in while_loop
    return checkpointed_while_loop(
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/equinox/internal/_loop/checkpointed.py", line 247, in checkpointed_while_loop
    body_fun_ = filter_closure_convert(body_fun_, init_val_)
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/equinox/internal/_loop/common.py", line 463, in new_body_fun
    buffer_val2 = body_fun(buffer_val)
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/diffrax/_integrate.py", line 618, in body_fun
    new_state, _, _ = body_fun_aux(state)
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/diffrax/_integrate.py", line 332, in body_fun_aux
    (y, y_error, dense_info, solver_state, solver_result) = solver.step(
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/diffrax/_solver/runge_kutta.py", line 1149, in step
    final_val = eqxi.while_loop(
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/equinox/internal/_loop/loop.py", line 107, in while_loop
    return checkpointed_while_loop(
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/equinox/internal/_loop/checkpointed.py", line 252, in checkpointed_while_loop
    _, _, _, final_val = _stop_gradient_on_unperturbed(init_val_, final_val_, body_fun_)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: Custom JVP rule must produce primal and tangent outputs with corresponding shapes and dtypes, but got:
  primal int32[] with tangent int32[], expecting tangent ShapedArray(float0[])
  primal bool[] with tangent bool[], expecting tangent ShapedArray(float0[])
  primal bool[] with tangent bool[], expecting tangent ShapedArray(float0[])
  primal int32[] with tangent int32[], expecting tangent ShapedArray(float0[])
  primal int32[] with tangent int32[], expecting tangent ShapedArray(float0[])

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/peternikopoulos/src/random/jax/diffrax_solve_ode_with_forcing_term.py", line 68, in <module>
    grads = solve(points)
            ^^^^^^^^^^^^^
  File "/Users/peternikopoulos/src/random/jax/diffrax_solve_ode_with_forcing_term.py", line 62, in solve
    sol = diffeqsolve(term, solver, t0, t1, dt0, y0, args=interp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/equinox/internal/_loop/checkpointed.py", line 1272, in _stop_gradient_on_unperturbed_jvp
    perturb_val = _resolve_perturb_val(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/equinox/internal/_loop/checkpointed.py", line 1241, in _resolve_perturb_val
    perturb_val = jax.eval_shape(_resolve_perturb_val_impl).value
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/equinox/internal/_loop/checkpointed.py", line 1214, in _resolve_perturb_val_impl
    jax.linearize(_to_linearize, dynamic)
  File "/Users/peternikopoulos/src/miniconda3/envs/isky/lib/python3.11/site-packages/equinox/internal/_loop/checkpointed.py", line 1207, in _to_linearize
    _out = _body_fun(_val)
           ^^^^^^^^^^^^^^^
TypeError: Custom JVP rule must produce primal and tangent outputs with corresponding shapes and dtypes, but got:
  primal int32[] with tangent int32[], expecting tangent ShapedArray(float0[])
  primal bool[] with tangent bool[], expecting tangent ShapedArray(float0[])
  primal bool[] with tangent bool[], expecting tangent ShapedArray(float0[])
  primal int32[] with tangent int32[], expecting tangent ShapedArray(float0[])
  primal int32[] with tangent int32[], expecting tangent ShapedArray(float0[])
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

</details>

<details>
<summary> Copy-Pasted code from docs </summary>

```python3
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
from diffrax import diffeqsolve, ODETerm, SaveAt, Tsit5

# change stderr to stdout to log error messages
import sys

sys.stderr = sys.stdout


def force(t, args):
    m, c = args
    return m * t + c


def vector_field(t, y, args):
    return -y + force(t, args)


@jax.jit
def solve(y0, args):
    term = ODETerm(vector_field)
    solver = Tsit5()
    t0 = 0
    t1 = 10
    dt0 = 0.1
    saveat = SaveAt(ts=jnp.linspace(t0, t1, 1000))
    sol = diffeqsolve(term, solver, t0, t1, dt0, y0, args=args, saveat=saveat)
    return sol


y0 = 1.0
args = (0.1, 0.02)
sol = solve(y0, args)

plt.plot(sol.ts, sol.ys)
plt.xlabel("t")
plt.ylabel("y")
# plt.show()


from diffrax import backward_hermite_coefficients, CubicInterpolation


def vector_field2(t, y, interp):
    return -y + interp.evaluate(t)


@jax.jit
@jax.grad
def solve(points):
    t0 = 0
    t1 = 10
    ts = jnp.linspace(t0, t1, len(points))
    coeffs = backward_hermite_coefficients(ts, points)
    interp = CubicInterpolation(ts, coeffs)
    term = ODETerm(vector_field2)
    solver = Tsit5()
    dt0 = 0.1
    y0 = 1.0
    sol = diffeqsolve(term, solver, t0, t1, dt0, y0, args=interp)
    (y1,) = sol.ys
    return y1


points = jnp.array([3.0, 0.5, -0.8, 1.8])
grads = solve(points) ########## FAILS HERE
```

</details>

**Comment by patrick-kidger** [comment]
This is a known issue with JAX 0.4.34. I've already got a workaround applied to Equinox HEAD (which you can upgrade to now if you need to; or downgrade JAX), and I will do a new release in the new few days.

**Comment by nikopoulospet** [comment]
thanks!
