### ISSUE TITLE
issue with diffrax 0.5.1

### ISSUE THREAD

**Issue by etienney** [patrick-kidger/diffrax#529]
Hello,

Diffrax 0.5.1 cannot load equinox anymore, probably due to a dependency problem.
Running the suggested basic example doesn't work
```
from diffrax import diffeqsolve, ODETerm, Dopri5

def f(t, y, args):
    return -y

term = ODETerm(f)
solver = Dopri5()
y0 = jnp.array([2., 3.])
solution = diffeqsolve(term, solver, t0=0, t1=1, dt0=0.1, y0=y0)
```

I get the following issues for this code on my cmd, I provide the pip list

```
`PS C:\Users\userrrr> & C:/Users/userrrr/AppData/Local/Programs/Python/Python39/python.exe c:/Users/userrrr/Desktop/diffraxtest.py
Traceback (most recent call last):
  File "c:\Users\userrrr\Desktop\diffraxtest.py", line 1, in <module>
    from diffrax import diffeqsolve, ODETerm, Dopri5
  File "C:\Users\userrrr\AppData\Local\Programs\Python\Python39\lib\site-packages\diffrax\__init__.py", line 3, in <module>
  File "C:\Users\userrrr\AppData\Local\Programs\Python\Python39\lib\site-packages\diffrax\_adjoint.py", line 7, in <module>
    import equinox as eqx
  File "C:\Users\userrrr\AppData\Local\Programs\Python\Python39\lib\site-packages\equinox\__init__.py", line 3, in <module>
    from . import debug as debug, internal as internal, nn as nn
  File "C:\Users\userrrr\AppData\Local\Programs\Python\Python39\lib\site-packages\equinox\debug\__init__.py", line 1, in <module>
    from ._announce_transform import announce_transform as announce_transform
  File "C:\Users\userrrr\AppData\Local\Programs\Python\Python39\lib\site-packages\equinox\debug\_announce_transform.py", line 11, in <module>
    from .._filters import combine, is_array, partition
  File "C:\Users\userrrr\AppData\Local\Programs\Python\Python39\lib\site-packages\equinox\_filters.py", line 11, in <module>
    AxisSpec = Union[bool, Callable[[Any], bool]]
  File "C:\Users\userrrr\AppData\Local\Programs\Python\Python39\lib\typing.py", line 243, in inner
    return func(*args, **kwds)
  File "C:\Users\userrrr\AppData\Local\Programs\Python\Python39\lib\typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "C:\Users\userrrr\AppData\Local\Programs\Python\Python39\lib\typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "C:\Users\userrrr\AppData\Local\Programs\Python\Python39\lib\typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'
PS C:\Users\userrrr> pip list
Package             Version
------------------- -----------
contourpy           1.3.0
cycler              0.12.1
diffrax             0.5.1
equinox             0.11.8
fonttools           4.55.0
importlib_metadata  8.5.0
importlib_resources 6.4.5
jax                 0.4.30
jaxlib              0.4.30
jaxtyping           0.2.36
kiwisolver          1.4.7
lineax              0.0.7
matplotlib          3.9.2
ml_dtypes           0.5.0
jaxtyping           0.2.36
kiwisolver          1.4.7
lineax              0.0.7
matplotlib          3.9.2
ml_dtypes           0.5.0
kiwisolver          1.4.7
lineax              0.0.7
matplotlib          3.9.2
ml_dtypes           0.5.0
ml_dtypes           0.5.0
numpy               2.0.2
opt_einsum          3.4.0
optimistix          0.0.9
packaging           24.2
pillow              11.0.0
pip                 24.3.1
pyparsing           3.2.0
python-dateutil     2.9.0.post0
scipy               1.13.1
setuptools          49.2.1
six                 1.16.0
typeguard           2.13.3
typing_extensions   4.12.2
zipp                3.21.0
PS C:\Users\userrrr>`
```

I need this older version for the way the library I use handle diffrax events, and as I understand it the problem comes from a too recent equinox version used in diffrax 0.5.1, would it be possible to try fixing this by demanding an older version of equinox for this version of diffrax ?

Thanks for diffrax and have a good day

**Comment by patrick-kidger** [comment]
Which version of Python is this? This looks like a known bug in early versions of Python `3.9.*`.

**Comment by etienney** [comment]
indeed It was due to this problem of Python versions. Thanks a lot and sorry
