### ISSUE TITLE
Diffrax can't seem to find a solution despite increasing max_steps

### ISSUE THREAD

**Issue by ma-sadeghi** [patrick-kidger/diffrax#85]
So far, I've tried using `float64`, and smaller `atol`/`rtol` values, but I get the same error. I also increased `max_steps` up to 16^6, but no luck.

To give a little bit of context, the system of ODEs I'm trying to solve here is method of lines discretization of the heat equation in 1D, initially at y = 1, with Dirichlet BCs imposed at the two boundaries.

To make sure that the problem is not ill-defined, I tried to solve it using `scipy`'s `solve_ivp` and it worked fine.

Would really appreciate it if you could shed some light.

```python
# Imports
import diffrax
import jax
import jax.numpy as jnp
jax.config.update("jax_enable_x64", False)

# Parameters
N = 1000
h = 1/(N+1)
y0 = jnp.ones(N, dtype="float32")    # IC: @t=0 ; y=1
y0 = y0.at[0].set(0.0)               # BC: @x=0 ; y=0
y0 = y0.at[0].set(0.0)               # BC: @x=L ; y=0
tspan = (0, 0.05)
saveat = jnp.linspace(*tspan, 10).tolist()
rtol = 1e-3
atol = 1e-5

# Define system of ODEs
def func(t, y, dy):
    idx = jnp.arange(1, N-1)
    dy = dy.at[idx].set((y[idx-1] - 2*y[idx] + y[idx+1]) / h**2)
    return dy

# Solve diffeq system using Diffrax
dy = jnp.zeros(N)
odefunc = lambda t, y, args: func(t, y, dy)
eqs = diffrax.ODETerm(odefunc)
solver = diffrax.Dopri5()
stepsize_controller = diffrax.PIDController(rtol=rtol, atol=atol)
t = diffrax.SaveAt(ts=saveat)

@jax.jit
def solve_diffrax(y0):
    return diffrax.diffeqsolve(eqs, solver, t0=tspan[0], t1=tspan[1], dt0=None,
                               y0=y0, saveat=t, max_steps=4*16**4,
                               stepsize_controller=stepsize_controller)

sol = solve_diffrax(y0)
```

```python
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
ERROR:absl:Outside call <function _call.<locals>.<lambda> at 0x7f5810336e50> threw exception The maximum number of solver steps was reached. Try increasing `max_steps`..
Traceback (most recent call last):
  File "/home/anaconda/Notebooks/Amin/pydns/tmp.py", line 38, in <module>
    sol = solve_diffrax(y0)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/_src/api.py", line 432, in cache_miss
    out_flat = xla.xla_call(
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/core.py", line 1709, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/core.py", line 1721, in call_bind
    outs = top_trace.process_call(primitive, fun, tracers, params)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/core.py", line 614, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/_src/dispatch.py", line 145, in _xla_call_impl
    out = compiled_fun(*args)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/_src/dispatch.py", line 444, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 1067, in wrapped_callback
    result_arrays = _outside_call_run_callback(
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 1203, in _outside_call_run_callback
    raise e  # Let the exception propagate
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 1146, in _outside_call_run_callback
    res = callback(arg, device, unpacked_transforms)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 719, in <lambda>
    callback = lambda arg, device, transforms: callback_func(arg)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/diffrax/misc/errors.py", line 35, in raises
    raise error_cls(msgs[_index.item()])
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: The maximum number of solver steps was reached. Try increasing `max_steps`.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anaconda/Notebooks/Amin/pydns/tmp.py", line 38, in <module>
    sol = solve_diffrax(y0)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 1067, in wrapped_callback
    result_arrays = _outside_call_run_callback(
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 1203, in _outside_call_run_callback
    raise e  # Let the exception propagate
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 1146, in _outside_call_run_callback
    res = callback(arg, device, unpacked_transforms)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/jax/experimental/host_callback.py", line 719, in <lambda>
    callback = lambda arg, device, transforms: callback_func(arg)
  File "/home/anaconda/mambaforge/envs/dev/lib/python3.9/site-packages/diffrax/misc/errors.py", line 35, in raises
    raise error_cls(msgs[_index.item()])
RuntimeError: The maximum number of solver steps was reached. Try increasing `max_steps`.
```

**Comment by patrick-kidger** [comment]
So this turned out to be a very-edge-case bug in Diffrax itself. If you're curious about the gory details then head on over to #86. The short version is that Diffrax does some extra stuff to improve numerical stability, that had an unintended interaction with adaptive stepping.

Once tests have passed over there I'll merge it + do a new release.

FYI, essentially unrelatedly, I think you have a couple of typos in your example. For one, you don't need to specify `dtype="float32"` in `y0` -- in fact this will result in the subsequent code throwing an error if using float64, as then you've forced this array to be float32 whilst everything else is float64. For another, your boundary condition at L is actually being imposed at 0 (you have the same boundary condition twice).

**Comment by ma-sadeghi** [comment]
Thanks for your quick reply! Yes, I meant to apply the second BC at `[-1]`. Thanks for the catch.

I just went over the PR, and indeed it was quite an edge case!

Regarding the `dtype`, right. I just realized that `jnp` by default produces `float32`.
