### ISSUE TITLE
RuntimeError: INTERNAL: Could not find the corresponding function

### ISSUE THREAD

**Issue by ma-sadeghi** [patrick-kidger/diffrax#88]
Sorry for spamming the issue tracker :)

Btw, this only happens with GPU-compatible `jax`.

```python
>>> import diffrax
2022-03-29 16:09:54.130864: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 9.1.108, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2022-03-29 16:09:54.135276: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:230] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 7.5
2022-03-29 16:09:54.135326: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:233] Used ptxas at ptxas
2022-03-29 16:09:54.137132: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:632] failed to get PTX kernel "convert_2" from module: CUDA_ERROR_NOT_FOUND: named symbol not found
2022-03-29 16:09:54.137185: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2140] Execution of replica 0 failed: INTERNAL: Could not find the corresponding function
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/__init__.py", line 17, in <module>
    from .integrate import diffeqsolve
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/integrate.py", line 29, in <module>
    from .solver import (
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/solver/__init__.py", line 1, in <module>
    from .base import (
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/solver/base.py", line 165, in <module>
    class AbstractImplicitSolver(AbstractSolver):
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/solver/base.py", line 166, in AbstractImplicitSolver
    nonlinear_solver: AbstractNonlinearSolver = NewtonNonlinearSolver()
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/equinox/module.py", line 116, in __call__
    cls.__init__(self, *args, **kwargs)
  File "<string>", line 9, in __init__
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/nonlinear_solver/newton.py", line 85, in __post_init__
    error_if(self.max_steps < 2, "max_steps must be at least 2.")
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/misc/errors.py", line 25, in error_if
    branched_error_if(pred, 0, [msg], error_cls)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/misc/errors.py", line 38, in branched_error_if
    lax.cond(pred, lambda: hcb.call(raises, index), lambda: None)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/_src/lax/control_flow.py", line 901, in cond
    return _cond(*args, **kwargs)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/_src/lax/control_flow.py", line 879, in _cond
    index = lax.convert_element_type(pred, np.int32)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 488, in convert_element_type
    return _convert_element_type(operand, new_dtype, weak_type=False)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 522, in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/core.py", line 286, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/core.py", line 289, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/core.py", line 611, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/_src/dispatch.py", line 94, in apply_primitive
    return compiled_fun(*args)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/_src/dispatch.py", line 114, in <lambda>
    return lambda *args, **kw: compiled(*args, **kw)[0]
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/jax/_src/dispatch.py", line 444, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: INTERNAL: Could not find the corresponding function

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/__init__.py", line 17, in <module>
    from .integrate import diffeqsolve
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/integrate.py", line 29, in <module>
    from .solver import (
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/solver/__init__.py", line 1, in <module>
    from .base import (
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/solver/base.py", line 165, in <module>
    class AbstractImplicitSolver(AbstractSolver):
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/solver/base.py", line 166, in AbstractImplicitSolver
    nonlinear_solver: AbstractNonlinearSolver = NewtonNonlinearSolver()
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/equinox/module.py", line 116, in __call__
    cls.__init__(self, *args, **kwargs)
  File "<string>", line 9, in __init__
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/nonlinear_solver/newton.py", line 85, in __post_init__
    error_if(self.max_steps < 2, "max_steps must be at least 2.")
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/misc/errors.py", line 25, in error_if
    branched_error_if(pred, 0, [msg], error_cls)
  File "/home/anaconda/mambaforge/envs/gpu2/lib/python3.9/site-packages/diffrax/misc/errors.py", line 38, in branched_error_if
    lax.cond(pred, lambda: hcb.call(raises, index), lambda: None)
RuntimeError: INTERNAL: Could not find the corresponding function
```

**Comment by ma-sadeghi** [comment]
Right, I just realized that it's indeed a `jax` issue. The reason I was fooled into thinking that it was a `diffrax` issue is that I was able to import `jax`. I just tried doing something useful, `jax.numpy.ones(5)` and there you go, the same error :)
